server:
  port: 8080

# spring
spring:
  profiles.include: 'apis, apps'

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    log-request-details: true

# SpringBoot default error page disable
error:
  whitelabel:
    enabled: false

################################################################################
# Jedis Config
################################################################################

jedis-client:
  max-total: 500
  max-wait-millis: 5000
  max-idle: 30
  min-idle: 20
  num-tests-pereviction-run: 5000
  time-between-eviction-runs-millis: 60000
  block-when-exhausted: true
  test-on-borrow: true
  test-on-return: true
  test-while-idle: true
  host: '127.0.0.1'
  port: 6379
  timeout: 1000
  database: 0

################################################################################
# Jetty Config
################################################################################

jetty-client:
  thread-count: 100
  max-connection: 500
  timeout: 5000

################################################################################
# Undefined Service Config
################################################################################

undefined:
  service:
    recognize-subdomain: false
    ip-acl-enable: false
    cluster:
      enable: false
      sync-interval: 300000
    interceptor:
      isasync: true
      async.thread.count: 100
    proxy-timeout: 20000

---
spring:
  profiles: local

undefined:
  service:
    ip-acl-enable: false
    cluster:
      enable: false
      sync-interval: 300000

---
spring:
  profiles: dev

undefined:
  service:
    ip-acl-enable: true
    cluster:
      enable: true
      sync-interval: 300000

################################################################################
# Jedis Config
################################################################################

jedis-client:
  max-total: 500
  max-wait-millis: 5000
  max-idle: 30
  min-idle: 20
  num-tests-pereviction-run: 5000
  time-between-eviction-runs-millis: 60000
  block-when-exhausted: true
  test-on-borrow: true
  test-on-return: true
  test-while-idle: true
  host: '127.0.0.1'
  port: 6379
  timeout: 1000
  database: 0

################################################################################
# Jetty Config
################################################################################

jetty-client:
  thread-count: 100
  max-connection: 500
  timeout: 5000
