server:
  port: 8080

# spring
spring:

  profiles:
    active: local
  profiles.include: 'apis'

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    log-request-details: true

################################################################################
# Jedis Config
################################################################################

jedis-client:
  max-total: 500
  max-wait-millis: 5000
  max-idle: 30
  min-idle: 20
  num-tests-pereviction-run: 5000
  time-between-eviction-runs-millis: 60000
  block-when-exhausted: true
  test-on-borrow: true
  test-on-return: true
  test-while-idle: true
  host: '127.0.0.1'
  port: 6379
  timeout: 1000

################################################################################
# Jetty Config
################################################################################

jetty-client:
  thread-count: 100
  max-connection: 500
  timeout: 5000

