server:
  port: 8080

# spring
spring:
  profiles.include: 'local, apis-local, apps-local'

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    log-request-details: true

# SpringBoot default error page disable
error:
  whitelabel:
    enabled: false

moon:
  service:proxy-timeout: 20000

logging:
  path: logs
---
spring.profiles: dev
spring.profiles.include: 'dev, apps-dev, apis-dev'
